config/routes.rb
Rails.application.routes.draw do
  resources :receipts

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
	validates :DatePaid, presence: true
	validates :ReceiptNo, numericality: true
	validates :AccountNo, numericality: true
	validates :ClientName, presence: true
	validates :AmountDeposited, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    @receipt = Receipt.new
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to receipts_path, notice: 'Receipt was successfully created.' }
        format.json { render action: 'index', status: :created, location: @receipt }
      else
        format.html { render action: 'new' }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @receipt }
      else
        format.html { render action: 'edit' }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:DatePaid, :ReceiptNo, :AccountNo, :ClientName, :AmountDeposited, :Status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Date_Paid %>
    <%= f.text_field :DatePaid %>
  </div>
  <div class="field">
    <%= f.label :Receipt_No %>
    <%= f.number_field :ReceiptNo %>
  </div>
  <div class="field">
    <%= f.label :Account_No %>
    <%= f.number_field :AccountNo %>
  </div>
  <div class="field">
    <%= f.label :Client_Name %>
    <%= f.text_field :ClientName %>
  </div>
  <div class="field">
    <%= f.label :Amount_Deposited %>
    <%= f.number_field :AmountDeposited %>
  </div>
  <div class="field">
    <%= f.label :Status %>
    <%= f.text_field :Status %>
  </div>
  <div class="actions"><br><br><br>
    <center>
    <%= f.submit "Issue PR" %>
    </center>  
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<div class="row">

<h1>Issue Provisional Receipt</h1>

  <div class="small-4 large-4 columns">
<%= render 'form' %>
</div>

  <div class="small-6 large-8 columns">

<table>
  <thead>
    <tr>
      <th>Date Paid</th>

      <th>Receipt No</th>
      <th>Account No</th>
      <th>Client Name</th>
      <th>Amount Deposited</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.DatePaid %></td>
        <td><%= receipt.ReceiptNo %></td>
        <td><%= receipt.AccountNo %></td>
        <td><%= receipt.ClientName %></td>
        <td><%= receipt.AmountDeposited %></td>
        <td><%= receipt.Status %></td>
        <td><%#= link_to 'Show', receipt %></td>
        <td><%#= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%#= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<%#= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date Paid:</strong>
  <%= @receipt.DatePaid %>
</p>

<p>
  <strong>Receipt No:</strong>
  <%= @receipt.ReceiptNo %>
</p>

<p>
  <strong>Account No:</strong>
  <%= @receipt.AccountNo %>
</p>

<p>
  <strong>Client Name:</strong>
  <%= @receipt.ClientName %>
</p>

<p>
  <strong>Amount Deposited:</strong>
  <%= @receipt.AmountDeposited %>
</p>

<p>
  <strong>Status:</strong>
  <%= @receipt.Status %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>